### PR TITLE
Hud Functions

### PR DESCRIPTION
**Pull request by abdulkadiraktas**
Hud element examples.

### CODE REVIEW

**Comment by itschip** [comment]
Can you provide some images here how it works?

**Comment by nearbyplayer** [comment]
Ask English please.

**Comment by itschip** [comment]
I am going to test what you have provided tonight, then let you know @abdulkadiraktas

**Comment by abdulkadiraktas** [comment]
> Also only in English please.

I edited script.

**Comment by abdulkadiraktas** [comment]
> Can you provide some images here on how it works?

screenshots

https://prnt.sc/v3a3ch

**Comment by itschip** [comment]
Seems fine 👍

**Pull request merged**
